[versions]
# KotlinX
kotlinx-coroutines-android = "1.6.1"

# AndroidX
androidx-core = "1.7.0"
androidx-appcompat = "1.4.1"
androidx-livedata = "2.4.1"
androidx-startup = "1.1.1"
androidx-junit = "1.1.3"

# Okio
okio = "3.0.0"

# Test
junit = "4.13.2"

[libraries]
# KotlinX
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines-android" }

# AndroidX
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-startup = { module = "androidx.startup:startup-runtime", version.ref = "androidx-startup" }
androidx-livedata = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "androidx-livedata" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-junit" }

# Okio
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }

# Test
junit = { module = "junit:junit", version.ref = "junit" }